export const postRegisterPath = '/register'
export const postLoginPath = '/login'
export const getAllUsers = '/users'
export const getProfile = '/users/me'
export const postCreateThread = '/threads'
export const getAllThreads = '/threads'
export const getAllLeaderboards = '/leaderboards'
export const postNewThread = '/threads'