export const POST_REGISTER_LOADING = 'POST_REGISTER_LOADING'
export const POST_REGISTER_FAILED = 'POST_REGISTER_FAILED'
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS'
export const CLEAR_REGISTER = 'CLEAR_REGISTER'

export const POST_LOGIN_LOADING = 'POST_LOGIN_LOADING'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'

export const OPEN_TOAST = 'OPEN_TOAST'