export const POST_REGISTER_LOADING = 'POST_REGISTER_LOADING'
export const POST_REGISTER_FAILED = 'POST_REGISTER_FAILED'
export const POST_REGISTER_SUCCESS = 'POST_REGISTER_SUCCESS'
export const CLEAR_REGISTER = 'CLEAR_REGISTER'

export const POST_LOGIN_LOADING = 'POST_LOGIN_LOADING'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const CLEAR_LOGIN = 'CLEAR_LOGIN'

export const OPEN_TOAST = 'OPEN_TOAST'

export const GET_THREADS_LOADING = 'GET_THREADS_LOADING'
export const GET_THREADS_SUCCESS = 'GET_ALL_THREADS'
export const GET_THREADS_FAILED = 'GET_THREADS_FAILED'
export const POST_THREADS_LOADING = 'POST_THREADS_LOADING'
export const POST_THREADS_SUCCESS = 'POST_ALL_THREADS'
export const POST_THREADS_FAILED = 'POST_THREADS_FAILED'

export const GET_LEADERBOARDS_LOADING = 'GET_LEADERBOARDS_LOADING'
export const GET_LEADERBOARDS_SUCCESS = 'GET_LEADERBOARDS_SUCCESS'
export const GET_LEADERBOARDS_FAILED = 'GET_LEADERBOARDS_FAILED'

export const GET_DETAIL_LOADING = 'GET_DETAIL_LOADING'
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS'
export const GET_DETAIL_FAILED = 'GET_DETAIL_FAILED'

export const POST_COMMENT_LOADING = 'POST_COMMENT_LOADING'
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'

export const GET_ALL_USERS_LOADING = 'GET_ALL_USERS_LOADING'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED'